CHARACTERISTICS = {
    "ABS": "АБС",
    "Adaptive Cruise Control": "Адаптивный круиз-контроль",
    "Alarm system": "Сигнализация",
    "Arm rest": "",
    "Automatic climatisation, 2 zones": "Автоматический кондиционер, 2 зоны",
    "Bi-xenon headlights": "Биксеноновые фары",
    "Cargo barrier": "Перегородка багажника",
    "DAB radio": "Цифровое радио",
    "Distance warning system": "Функция контроля сближения",
    "Electric tailgate": "Электропривод двери багажника",
    "Emergency call system": "",
    "Emergency tyre repair kit": "Комплект для аварийного ремонта шин",
    "ESP": "ESP",
    "Headlight washer system": "Омыватель фар",
    "Heated windshield": "Подогрев лобового стекла",
    "High beam assist": "Ассистент дальнего света",
    "Hill-start assist": "Система помощи при трогании на подъеме",
    "Leather steering wheel": "Кожаный руль",
    "Lumbar support": "Подушка для поясницы",
    "Passenger seat Isofix point": "Isofix на пасажирском сидении",
    "Sound system": "Звуковая система",
    "Traffic sign recognition": "Распознавание дорожных знаков",
    "Trailer coupling fix": "",
    "Tyre pressure monitoring": "Датчики давления в шинах",
    "Adaptive cornering lights": "Адаптивное освещение поворотов",
    "Android Auto": "Android Auto",
    "Apple CarPlay": "Apple CarPlay",
    "Autom. dimming interior mirror": "Система затемнения зеркала заднего вида",
    "Bluetooth": "Bluetooth",
    "Fatigue warning system": "Система контроля усталости водителя",
    "Induction charging for smartphones": "Беспроводная зарядка",
    "Integrated music streaming": "",
    "LED running lights": "Светодиодные фары",
    "Speed limit control system": "Система ограничения скорости",
    "Summer tyres": "Летние шины",
    "Trailer coupling, swiveling": "",
    "USB port": "Порт USB",
    "Voice control": "Комплект громкой связи",
    "WLAN / WiFi hotspot": "WLAN / WiFi hotspot",
    "Ambient lighting": "Контурная подсветка",
    "Electric heated rear seats": "Подогрев задних сидений",
    "Automatic climatisation, 3 zones": "Автоматический кондиционер, 3 зоны",
    "Touchscreen": "Тачскрин",
    "Winter package": "Зимний пакет",
    "Glare-free high beam headlights": "Система предотвращения ослепление встречного автомобиля",
    "Smoker's package": "Пакет курильщика",
    "Spare tyre": "",
    "Steel wheels": "Стальные диски",
    "Trailer coupling, detachable": "",
    "Fold flat passenger seat": "",
    "Winter tyres": "Зимние шины",
    "Heated steering wheel": "Подогрев руля",
    "Digital cockpit": "Цифровая приборная панель",
    "Paddle shifters": "",
    "Automatic climatisation, 4 zones": "Автоматический кондиционер, 4 зоны",
    "Emergency tyre": "",
    "All season tyres": "Всесезонные шины",
    "Electric backseat adjustment": "",
    "Massage seats": "Масажер в сидениях",
    "Night vision assist": "Система ночного видения",
    "Adaptive Lighting": "Адаптивные фары",
    "AFS": "Адаптивные фары"
}


class Translator:
    @staticmethod
    def translate_characteristic(characteristic):
        translated_characteristic = CHARACTERISTICS.get(characteristic)
        if translated_characteristic:
            return translated_characteristic
        else:
            return characteristic
